Traceback (most recent call last):
  File "../kuhn3p/players/UltimateAIKuhn/connect_to_dealer.py", line 48, in <module>
    player.start_hand(position, cards[position])
  File "/Users/maxchiswick/ml/aipoker/acpcw/kuhn3p/players/UltimateAIKuhn/kuhn3p/players/Ultimate_ai_khun.py", line 332, in start_hand
    '.csv', header=None, index_col=0, delimiter=',')
  File "/Users/maxchiswick/opt/miniconda3/envs/py2/lib/python2.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/maxchiswick/opt/miniconda3/envs/py2/lib/python2.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/maxchiswick/opt/miniconda3/envs/py2/lib/python2.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/Users/maxchiswick/opt/miniconda3/envs/py2/lib/python2.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/maxchiswick/opt/miniconda3/envs/py2/lib/python2.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: [Errno 2] File kuhn3p/players/strategies/strategy1.csv does not exist: 'kuhn3p/players/strategies/strategy1.csv'
